// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 08/01/2026 19:22:51
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/plugins/**/*.{js,ts,mjs}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/composables/**/*.{js,ts,mjs}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/utils/**/*.{js,ts,mjs}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/rstinus/Documents/CiteEngrenage/SiteWebUtilisateur/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;